# Generated by Django 6.0.2 on 2026-05-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_subpost_cloudinary_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='aspect_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subpost',
            name='aspect_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
