# Generated by Django 5.1.7 on 2026-05-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_post_aspect_ratio_subpost_aspect_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='duration',
            field=models.FloatField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='size',
            field=models.PositiveBigIntegerField(blank=True, help_text='Size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='subpost',
            name='duration',
            field=models.FloatField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='subpost',
            name='size',
            field=models.PositiveBigIntegerField(blank=True, help_text='Size in bytes', null=True),
        ),
    ]
