# Generated by Django 5.1.7 on 2026-05-13 18:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_post_duration_post_size_subpost_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='media'),
        ),
        migrations.AlterField(
            model_name='subpost',
            name='media_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='media'),
        ),
    ]
