# Generated by Django 5.1.7 on 2026-06-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_replace_post_category_with_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='priority_status',
            field=models.CharField(choices=[('punished', 'Punished'), ('normal', 'Normal'), ('trending', 'Trending')], default='normal', help_text='Editorial weight used by the trending algorithm.', max_length=20),
        ),
    ]
