# Generated by Django 5.1.7 on 2026-07-29 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_captionmoderationevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_media_deleted', '-created_at'], name='post_feed_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'is_media_deleted', '-created_at'], name='post_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='post_author_created_idx'),
        ),
        migrations.AddIndex(
            model_name='subpost',
            index=models.Index(fields=['parent_post', 'is_media_deleted', '-created_at'], name='subpost_parent_created_idx'),
        ),
    ]
