# Generated by Django 5.1.7 on 2026-07-28 04:19

from django.db import migrations, models


def create_initial_download_counter(apps, schema_editor):
    ApkDownloadCounter = apps.get_model('core', 'ApkDownloadCounter')
    ApkDownloadCounter.objects.get_or_create(pk=1, defaults={'count': 3017})


def remove_initial_download_counter(apps, schema_editor):
    ApkDownloadCounter = apps.get_model('core', 'ApkDownloadCounter')
    ApkDownloadCounter.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApkDownloadCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveBigIntegerField(default=3017)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(
            create_initial_download_counter,
            remove_initial_download_counter,
        ),
    ]
