# Generated by Django 6.0.2 on 2026-06-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userviolation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_completed_profile',
            field=models.BooleanField(default=False),
        ),
    ]
