# Generated by Django 5.1.7 on 2026-07-22 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_has_completed_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=320)),
                ('message_id', models.CharField(blank=True, max_length=160)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment or bullying'), ('hate', 'Hate or identity attack'), ('threat', 'Threat or violence'), ('sexual', 'Sexual content'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reported_user', '-created_at'], name='users_chatr_reporte_633e8b_idx'), models.Index(fields=['room_id', '-created_at'], name='users_chatr_room_id_255427_idx')],
            },
        ),
    ]
