# Generated by Django 6.0.2 on 2026-02-15 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_initial'),
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='closebuddy',
            name='buddy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_buddies_target', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='closebuddy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_buddies_initiator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postapproval',
            name='buddy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postapproval',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='content.post'),
        ),
        migrations.AddField(
            model_name='vote',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='content.post'),
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='closebuddy',
            unique_together={('user', 'buddy')},
        ),
        migrations.AlterUniqueTogether(
            name='postapproval',
            unique_together={('post', 'buddy')},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('post', 'user')},
        ),
    ]
