# Generated by Django 6.0.2 on 2026-02-15 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_buddyrequest_closebuddyrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='buddyrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='buddyrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='closebuddy',
            name='buddy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_buddy_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='closebuddy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_close_buddies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CloseBuddyRequest',
        ),
    ]
