# Generated by Django 6.0.2 on 2026-05-07 11:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_buddy_system_rework'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buddy',
            new_name='Follow',
        ),
    ]
