# Generated by Django 5.1.7 on 2026-05-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closebuddyrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('ignored', 'Ignored')], default='pending', max_length=10),
        ),
    ]
