# Generated by Django 5.1.7 on 2026-06-17 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_post_media_file_alter_subpost_media_file'),
        ('social', '0009_alter_closebuddyrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPostVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('sub_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='content.subpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_subpost_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sub_post', 'user')},
            },
        ),
    ]
