# Generated by Django 5.1.7 on 2026-07-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_community_communitymembership_community_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='community_pics/'),
        ),
    ]
